### PR TITLE
Make CI capable of detecting failures.

### PR DESCRIPTION
**Pull request by yvantor**
This PR proposes an alternative CI flow so that is capable of detecting if tests succeeded or not. It also speeds up the checks using parallel runs.

### CODE REVIEW

**Comment by FrancescoConti** [comment]
Interesting that this is an "enhancement" :) I would call it a bugfix, I don't see much use in  regression tests that do not detect failures!

**Comment by yvantor** [comment]
> Interesting that this is an "enhancement" :) I would call it a bugfix, I don't see much use in regression tests that do not detect failures!

Done :)

**Comment by yvantor** [comment]
@OttG I am only waiting on @alex96295 feedback about the updated CI flow and for his merge, after that this should be ready.

**Comment by yvantor** [comment]
> @OttG I am only waiting on @alex96295 feedback about the updated CI flow and for his merge, after that this should be ready.

Unleash the Jeanmark

**Comment by OttG** [comment]
Unleashing

**Pull request merged**
