### PR TITLE
Add CI flow to standalone pulp_cluster

### PR DESCRIPTION
**Pull request by alex96295**
* Add CI flow
* Fix missing licenses

### CODE REVIEW

**Comment by luca-valente** [comment]
Looks amazing! We need to double-check the few tests that pass in less than one minute (`testMCHAN_pe_fc_basic`, `testMCHAN_TCDM2TCDM_tx_rx`, `LU/golden`, `Dijkstra/golden`). The golden ones don't look like real tests, the fabric controller one, it shouldn't be executed by the cluster's PE. No idea on the TCDM2TCDM one though.

**Comment by alex96295** [comment]
> Looks amazing! We need to double-check the few tests that pass in less than one minute (`testMCHAN_pe_fc_basic`, `testMCHAN_TCDM2TCDM_tx_rx`, `LU/golden`, `Dijkstra/golden`). The golden ones don't look like real tests. The `testMCHAN_pe_fc_basic` one shouldn't be executed by the cluster's PE. No idea about the TCDM2TCDM one though.

okay maybe we can remove the unneeded ones, can you handle that please? I think you know them best; also few representative tests are okay

**Comment by luca-valente** [comment]
@alex96295 done!
@OttG @micprog shall we merge when the CI passes?

**Comment by alex96295** [comment]
> @alex96295 done! @OttG @micprog shall we merge when the CI passes?

Thanks @luca-valente, lgtm on my side

**Comment by OttG** [comment]
LGTM as well

**Pull request merged**
