### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by micprog**
- Update build flow/testbench
- Fix testbench for badly addressed bursts
- Add types to all parameters
- Replace AXI interfaces with structs

### CODE REVIEW

**Comment by micprog** [comment]
I can also split this PR up a bit, there are quite a few changes coming together here...

**Review by yvantor — COMMENTED** [review]
The PR looks good to me. I just noticed that the DMA tests [do not even start])https://iis-git.ee.ethz.ch/github-mirror/pulp_cluster/-/jobs/996194#L26), and the same is for the parallel bare tests.

**Comment by micprog** [comment]
There were some more issues due to bad testing on my part, sorry. Should be fixed now (with some speed improvements and no more warnings). Might also be worth it to ensure the CI works properly and reports fails when it should...

**Comment by yvantor** [comment]
> There were some more issues due to bad testing on my part, sorry. Should be fixed now (with some speed improvements and no more warnings). Might also be worth it to ensure the CI works properly and reports fails when it should...
I think the problem is that it greps for a fatal or some error message (linked to the returned value I think) to understand that test failed, and if it does not it just returns success. I agree that this should be improved. Also making the regression output more homogeneous (like all of them printing "Success!" or "Failed!" at the end) could maybe help.

**Comment by yvantor** [comment]
@OttG as soon as @micprog merges [#44] and the CI completes, this can also be merged.

**Comment by OttG** [comment]
Everything seems fine now, CI is passing. Are we waiting for some other changes or I can merge?

**Pull request merged**
